//
// Generated file, do not edit! Created by nedtool 5.6 from mods/modules/messages/RSUBeacon.msg.
//

#ifndef __VEINS_RSUBEACON_M_H
#define __VEINS_RSUBEACON_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// cplusplus {{
#include "veins/base/utils/Coord.h"
#include "veins/modules/messages/DemoSafetyMessage_m.h"
#include "veins/base/utils/SimpleAddress.h"
// }}


namespace veins {

/**
 * Class generated from <tt>mods/modules/messages/RSUBeacon.msg:29</tt> by nedtool.
 * <pre>
 * packet RSUBeacon extends DemoSafetyMessage
 * {
 *     int POIID;
 * }
 * </pre>
 */
class RSUBeacon : public ::veins::DemoSafetyMessage
{
  protected:
    int POIID;

  private:
    void copy(const RSUBeacon& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const RSUBeacon&);

  public:
    RSUBeacon(const char *name=nullptr, short kind=0);
    RSUBeacon(const RSUBeacon& other);
    virtual ~RSUBeacon();
    RSUBeacon& operator=(const RSUBeacon& other);
    virtual RSUBeacon *dup() const override {return new RSUBeacon(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getPOIID() const;
    virtual void setPOIID(int POIID);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const RSUBeacon& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, RSUBeacon& obj) {obj.parsimUnpack(b);}

} // namespace veins

#endif // ifndef __VEINS_RSUBEACON_M_H

