//
// Generated file, do not edit! Created by nedtool 5.6 from mods/modules/messages/TaxiBeacon.msg.
//

#ifndef __VEINS_TAXIBEACON_M_H
#define __VEINS_TAXIBEACON_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// cplusplus {{
#include "veins/base/utils/Coord.h"
#include "veins/modules/messages/DemoSafetyMessage_m.h"
#include "veins/base/utils/SimpleAddress.h"
// }}


namespace veins {

/**
 * Class generated from <tt>mods/modules/messages/TaxiBeacon.msg:31</tt> by nedtool.
 * <pre>
 * packet TaxiBeacon extends DemoSafetyMessage
 * {
 * }
 * </pre>
 */
class TaxiBeacon : public ::veins::DemoSafetyMessage
{
  protected:

  private:
    void copy(const TaxiBeacon& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const TaxiBeacon&);

  public:
    TaxiBeacon(const char *name=nullptr, short kind=0);
    TaxiBeacon(const TaxiBeacon& other);
    virtual ~TaxiBeacon();
    TaxiBeacon& operator=(const TaxiBeacon& other);
    virtual TaxiBeacon *dup() const override {return new TaxiBeacon(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TaxiBeacon& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TaxiBeacon& obj) {obj.parsimUnpack(b);}

} // namespace veins

#endif // ifndef __VEINS_TAXIBEACON_M_H

